language: node_js
env:
  global:
    - secure: WvTJpEOLPIStsqRkHfQUdap1BUOyi0s+8R1nWBgn71MDgmTJQ4Y+QnKUektWplvJ0zvfHIXpilivDyQ8W1lCUFCWY9cnkvMnbrNhkRH0A6AkTce/YVU0ce6F5f0CpMF6+Pgikv8UacmBGka5aInEL/U7X6rteZLFHzJ/JPq/LrY=
    - secure: SvWD4pPHyRhjBH9PL0FcOxDUI5Fmr1Bc7Ff0P+Pvpsgh6YSD8adpIMb8s/q1TLdLvCMf5APF6z/Si5QM0qhFgqlRafpMtPfcT6llHw8HET3bzVAMV/kjZ+2crtN+1P00RAYrgDJYKfDuGw4EKPOSbIBxQ7pA/WOVibl3EQbiGL0=
addons:
  sauce_connect: true
node_js:
  - "0.10"
after_script:
  -
